### ISSUE TITLE
Users unable to complete surveys on steps mobile app

### ISSUE THREAD

**Issue by faith-mutua** [onaio/steps-app#135]
When an interviewer fills in the form after a participant has been selected, the survey is not marked as complete. The interviewer is stuck on the consent page and can only leave the page by selecting any of the other consent options. This results in not having any surveys marked as complete in both the **View Totals** page and on the web app. 

NB. One is only able to fill in the form when using ODK Collect v1.28.0 refer to this [comment ](https://github.com/onaio/steps-app/issues/123#issuecomment-968875561) for more information. 
The filled in data can still be submitted to the server and can be viewed in the respective form in ona.io.

**Comment by hilpitome** [comment]
To make sure the survey works as expected, ensure that you have downloaded the form with the label `WHO STEPS Instrument v31` whose ID is `STEPS_Instrument_V3_1`. The previous form was not working because the instance_name which ensures it is compatible in STEPS app was missing in the settings sheet of the XLS form

**Comment by faith-mutua** [comment]
@hilpitome noted. I'll let you know how it goes after testing with the correct form

**Comment by faith-mutua** [comment]
@hilpitome the app works seamlessly with the correct form. Surveys are marked as complete once a user has filled in the form. Closing this issue. cc @akahure
