### ISSUE TITLE
Preload data in the ODK form.

### ISSUE THREAD

**Issue by owais-vd** [onaio/steps-app#146]
**Description**
When a user taps on a button `INTERVIEW NOW` then we need to create a CSV file in `steps` internal storage and share it with the `ODK collect` app before launching a form.

**Comment by akahure** [comment]
More context, in the previous implementation, when we click the button _' Interview Now'_  the workflow would mean that we write a CSV file in the ODK forms directory and after that, we launch the ODK application, 

Now with the current restrictions, we are not allowed to write a CSV file in the ODK because the form directory is not publicly available. How do we handle this, with this limitation, 

Owais proposes: can we create a dedicated activity in the ODK app which will get the CSV file from a URI and write in their internal forms folder but the problem here in the steps app we have to launch this activity every time before launching a form activity.

**Comment by ukanga** [comment]
Can we have a short meeting on this to get a better understanding of the proposal and the options we have? Also, which versions of Android are affected?

**Comment by owais-vd** [comment]
Here is the currently proposed solution, we can create a dedicated activity in the ODK that will collect the CSV file from the URI and save this file to its internal storage form directory. A caveat here is if go with this solution then in the `steps` app side, we will need to call the form receiver activity every time for sending a CSV file before opening the actual form activity.

@ekigamba suggested a link https://docs.getodk.org/launch-apps-from-collect/#external-apps-to-populate-multiple-fields i'll also look into that

**Comment by akahure** [comment]
From discussions this Owais: 
Essentially we don't need storage because in this case, we are not uploading any CSV file in ODK, when a user taps on the launch button in ODK form, it will call an external app (STEPS) and get the data from the ODK form with values i.e. count the number of household or participants.
What we need to do: In steps, we need to create an activity that will be responsible to collect the dynamic values from steps. i.e. household count and also modified the XLS form according to this https://docs.getodk.org/launch-apps-from-collect/#external-apps-to-populate-multiple-fields

@owais-vd and @ekigamba 

1. Does this solution sound feasible and what are some of the potential gaps 
2. also will this be custom or can be adopted mainstream since Kaznet could potentially have the same issu and:
3. @ekigamba what LOE are we potentially looking at and I can put in a request for this next week (ball park estimation is finne)

**Comment by ekigamba** [comment]
1. It sounds feasible. Depending on how often the users change the forms, we'll need to communicate clearly how to updated or create new forms with the autofilled fields
2. Yes, this could be adopted mainstream since it only requires the changes on either Kaznet and STEPs and is dynamic enough to allow for string, integer, decimal, image, video, audio and file fields
3. 2-3 days

The work requires:
- Saving the current household under interview
- Creating an activity/content provider to requested household/participant data
- Writing tests
- Testing the integrations
- Updating all forms created by WHO for STEPs
- Create clear documentation and examples on supported `ex:` strings and how to use them

**Comment by akahure** [comment]
Confirmed that we can proceed https://github.com/onaio/steps-app/issues/146#issuecomment-1053993549 

@owais-vd
